aws_access_key = "xxxxxx"
aws_secret_key = "xxxxxx"
myami = "ami-0583d8c7a9c35822c"
mykey = "mykey"
tags = ["postgresql", "nodejs", "react"]
instancetype = "t2.micro"
controlinstancetype = "t3a.medium"
num = 3
region = "us-east-1"
mysecgr = "mern-project"
user = "engin"